name: nexstream
description: A new Flutter project for a Nexstream login screen.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is optional but recommended for private projects.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  another_flushbar: ^1.10.30
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Include any assets your application uses.




  # Include any fonts you are using.
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
