// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ilKvjx9QlvCf40x7IdG-LT5ZbZ-zfww',
    appId: '1:506794822616:web:2b73333968b84ba98640ad',
    messagingSenderId: '506794822616',
    projectId: 'nexstreamlive-46978',
    authDomain: 'nexstreamlive-46978.firebaseapp.com',
    storageBucket: 'nexstreamlive-46978.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB77xRzF1HyGi7bda-_K14BlMgajM5zN8',
    appId: '1:506794822616:android:06dee7c22c9790a48640ad',
    messagingSenderId: '506794822616',
    projectId: 'nexstreamlive-46978',
    storageBucket: 'nexstreamlive-46978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAm4K_-TYBwdzePPIE_htAV1akOOEVnk',
    appId: '1:506794822616:ios:f6c68255d1d00e5b8640ad',
    messagingSenderId: '506794822616',
    projectId: 'nexstreamlive-46978',
    storageBucket: 'nexstreamlive-46978.appspot.com',
    iosBundleId: 'com.example.nextstream1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAm4K_-TYBwdzePPIE_htAV1akOOEVnk',
    appId: '1:506794822616:ios:f6c68255d1d00e5b8640ad',
    messagingSenderId: '506794822616',
    projectId: 'nexstreamlive-46978',
    storageBucket: 'nexstreamlive-46978.appspot.com',
    iosBundleId: 'com.example.nextstream1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ilKvjx9QlvCf40x7IdG-LT5ZbZ-zfww',
    appId: '1:506794822616:web:a182aab9fb678baf8640ad',
    messagingSenderId: '506794822616',
    projectId: 'nexstreamlive-46978',
    authDomain: 'nexstreamlive-46978.firebaseapp.com',
    storageBucket: 'nexstreamlive-46978.appspot.com',
  );
}
